name: Publish nuget package

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the package'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Run PowerShell script
        env:
          nugetApiKey: ${{ secrets.NUGETAPIKEY }}
        run: |
          $version = "${{ github.event.inputs.version }}"
          pwsh -File ./src/nuget-pack.ps1 -packageId "SlowCow.Setup" -version "$version"
          pwsh -File ./src/nuget-pack.ps1 -packageId "SlowCow.Updater" -version "$version"

