name: Publish nuget package

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the package'
        required: false

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"

      - name: Run PowerShell script
        run: |
          $version = "${{ github.event.inputs.version }}"
          if ($null -ne $version) {
            pwsh -File ./src/SlowCow.Setup/nuget-pack.ps1 -version $version
          } else {
            pwsh -File ./src/SlowCow.Setup/nuget-pack.ps1
          }
